name:                embedded
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/embedded#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - file-embed
  - scotty
  - wai-app-static
  - warp

executables:
  embedded:
    source-dirs:      src
    main:             Main.hs
